// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA25VZYB7xlokMDvJgPenMllGwrxi5CNFY',
    appId: '1:1011213227517:web:c9dfde91adabe967cb7594',
    messagingSenderId: '1011213227517',
    projectId: 'growth-guards',
    authDomain: 'growth-guards.firebaseapp.com',
    storageBucket: 'growth-guards.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3jsABXkRn0q1LbhgY0-06reWEfVxRgtQ',
    appId: '1:1011213227517:android:71e0fa2bc19068bfcb7594',
    messagingSenderId: '1011213227517',
    projectId: 'growth-guards',
    storageBucket: 'growth-guards.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQgG3tj144YeZs68JhGP9fNr6HhckXPyw',
    appId: '1:1011213227517:ios:1dd71da25853b8fdcb7594',
    messagingSenderId: '1011213227517',
    projectId: 'growth-guards',
    storageBucket: 'growth-guards.appspot.com',
    iosBundleId: 'com.example.design',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQgG3tj144YeZs68JhGP9fNr6HhckXPyw',
    appId: '1:1011213227517:ios:53cd8949b80873becb7594',
    messagingSenderId: '1011213227517',
    projectId: 'growth-guards',
    storageBucket: 'growth-guards.appspot.com',
    iosBundleId: 'com.example.design.RunnerTests',
  );
}
